// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYjUI4yyjPbDNmwviwkXL_IqLcshkJ7oA',
    appId: '1:598682468279:web:efd1992d2a3701ffa03232',
    messagingSenderId: '598682468279',
    projectId: 'loginautosiste',
    authDomain: 'loginautosiste.firebaseapp.com',
    storageBucket: 'loginautosiste.appspot.com',
    measurementId: 'G-525D4CPWBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpugPFeYGmkGgmJmwWI47pFOe74NH8vuo',
    appId: '1:598682468279:android:cf40aae0303f75cda03232',
    messagingSenderId: '598682468279',
    projectId: 'loginautosiste',
    storageBucket: 'loginautosiste.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkCH8R8ej2ll2YhV7sh5Y18e473eWzuiY',
    appId: '1:598682468279:ios:03b0a6461a95e7d5a03232',
    messagingSenderId: '598682468279',
    projectId: 'loginautosiste',
    storageBucket: 'loginautosiste.appspot.com',
    iosBundleId: 'com.example.autosistebolivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkCH8R8ej2ll2YhV7sh5Y18e473eWzuiY',
    appId: '1:598682468279:ios:03b0a6461a95e7d5a03232',
    messagingSenderId: '598682468279',
    projectId: 'loginautosiste',
    storageBucket: 'loginautosiste.appspot.com',
    iosBundleId: 'com.example.autosistebolivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYjUI4yyjPbDNmwviwkXL_IqLcshkJ7oA',
    appId: '1:598682468279:web:d9fb692d8630e807a03232',
    messagingSenderId: '598682468279',
    projectId: 'loginautosiste',
    authDomain: 'loginautosiste.firebaseapp.com',
    storageBucket: 'loginautosiste.appspot.com',
    measurementId: 'G-BH1FGZK4K3',
  );
}
